import './globals.css'
import type { Metadata } from 'next'
import { Navbar } from '@/components/navbar'
import css from './layout.module.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={css.wrapper}>
        <Navbar />
        {children}
      </body>
    </html>
   )
}
